markdown: kramdown
highlighter: rouge

permalink: pretty

include: [.well-known, .well-known/apple-developer-domain-association.txt]
keep_files: [.well-known, .well-known/apple-developer-domain-association.txt]
